### ISSUE TITLE
Newly synced trip destination not showing immediately in Trip Builder using android package

### ISSUE THREAD

**Issue by seanflynncontact** [Sitata/issue_tracking#15]
When Trip Builder opens for the 1st time after newly syncing it does not show the destinations
Note: We are calling MySitata.Ctrlr.Jobs.Sync.All().Start(); 
This issue was resolved in iOS but still happens in Android

Android:
Log in to the app
Sync a new trip
Click the sitata landing page button
(New sync happens behind the scene)
Because its user first time going to the landing page Trip Builder launches
Issue: Country is not synced
Note: Subsequently clicking Edit Trip shows the destination correctly

**Comment by astjohn** [comment]
On iOS, this was simply due to a lack of Syncing information at the appropriate times.

This is likely due to the workflow on the app vs your backend and such. i.e. The sync with Sitata has to happen before the user tries to access a part of the application pertaining to the Sitata content.

With the workflow suggested to your team (by email) regarding streamlining the opt-in process, I think this will be less of a concern.

Essentially, if Sitata has the trip recorded on our backend, a proper workflow surrounding the sync process will likely eliminate this apparent delay. 


You need to get the Sitata traveller token to the device and synced in a timely manner. Therefore, when someone opts-in to the services, you should send the traveller token back to the device at that point in time and initiate a sync.

In addition, you should probably try to sync your user's TII profile data and sync Sitata's date (if traveller token present) when someone starts the application.

That should take care of the syncing issues. However, one edge case is if a policy and/or Sitata trip is created when the user has the app open or in the background. In this case, if you're sending a push notification, you could potentially sync data at that point in time too.

**Comment by seanflynncontact** [comment]
John. We are properly syncing and getting the trip id back prior to this taking place. 
According to Matt you made a ios package fix for this.
