### ISSUE TITLE
In Emergency Numbers, incorrect country is loaded

### ISSUE THREAD

**Issue by mattmalinoski** [Sitata/issue_tracking#17]
For a trip in Aruba, the Emergency Numbers screen showed USA instead of Aruba. This is the only time we've noticed this happening.

**Comment by astjohn** [comment]
@mattmalinoski - The behavior of emergency numbers looks like this:

If the user has enabled location / GPS Permissions then:

==> Open page to the country the user is currently located in.

Otherwise:

==> Open page to country that corresponds to itinerary.


If it takes a while to lock onto the user's location then the emergency numbers screen might go to the page corresponding to the itinerary and then quickly flip to the country the user is currently in.


I'm guessing that the person using the device was in the US and that's why this happened. If that's not the case, let me know and I can reopen this and investigate further.
