### ISSUE TITLE
Can't create a trip in iOS using company key

### ISSUE THREAD

**Issue by mattmalinoski** [Sitata/issue_tracking#4]
I get the "Uh oh!" message when I try to save a trip.

**Comment by astjohn** [comment]
@mattmalinoski - [This is likely by design](http://docs.sitata.com/sdk/v1/index.html#typical-use-case).

The company key (aka server key - perhaps we should rename it?) only grants access to endpoints in our api that [meant for server to server](http://docs.sitata.com/api/v1/index.html#company-vs-end-user). It's likely if you use the company key within the SDK that nothing will sync and almost all requests will be rejected.

The intention is that companies using our API/SDKs will create a trip on behalf of the traveller and then use the traveller's token with the SDKs.
